/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simoncherry_averageface_JNIUtils */

#ifndef _Included_com_simoncherry_averageface_JNIUtils
#define _Included_com_simoncherry_averageface_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simoncherry_averageface_JNIUtils
 * Method:    doGrayScale
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_averageface_JNIUtils_doGrayScale
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_averageface_JNIUtils
 * Method:    doEdgeDetection
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_averageface_JNIUtils_doEdgeDetection
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_averageface_JNIUtils
 * Method:    doBinaryzation
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_simoncherry_averageface_JNIUtils_doBinaryzation
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_simoncherry_averageface_JNIUtils
 * Method:    testParseJson
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_simoncherry_averageface_JNIUtils_testParseJson
(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
